### ISSUE TITLE
sapper example

### ISSUE THREAD

**Issue by phelbas** [ArthurClemens/dialogic#11]
Is there a working demo with sapper?

Trying to use it with sapper so I modified _layout by adding import and so on, but get an ERR_REQUIRE_ESM error on npm run dev 

undoing change to _layout removed error

**Comment by ArthurClemens** [comment]
No, I don't have any experience with Sapper. Do you have a project setup to share?

**Comment by ArthurClemens** [comment]
I found this explanation: https://stackoverflow.com/a/64071939/505157

Moving `dialogic-svelte` to `devDependencies` did solve the issue for me.

**Comment by ArthurClemens** [comment]
The package now also contains a demo for SvelteKit.
